Vagrant.configure("2") do |config|

	config.vm.define :balanceador do |balanceador|
		balanceador.vm.box = "bento/centos-7.9"
		balanceador.vm.network :private_network, ip: "192.168.50.10"
		balanceador.vm.hostname = "balanceador"
		balanceador.vm.provision "shell", path: "script-pf2/balanceador.sh"
	end
		config.vm.define :web1 do |web1|
		web1.vm.box = "bento/centos-7.9"
		web1.vm.network :private_network, ip: "192.168.50.11"
		web1.vm.hostname = "web1"
		web1.vm.provision "shell", path: "script-pf2/webserver11.sh"
	end
		config.vm.define :web2 do |web2|
		web2.vm.box = "bento/centos-7.9"
		web2.vm.network :private_network, ip: "192.168.50.12"
		web2.vm.hostname = "web2"
		web2.vm.provision "shell", path: "script-pf2/webserver12.sh"
	end
end